[package]
name = "kittycad-modeling-api-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
futures = "0.3.30"
image = "0.24.7"
kittycad = "0.2.37"
reqwest = "0.11.22"
serde = "1.0.189"
serde_json = "1.0.107"
tokio = { version = "1.33.0", features = ["macros", "rt"] }
tokio-tungstenite = "0.20.1"
uuid = "1.5.0"
